// Bibliothèque de défis intégrée : utilisée quand l'IA n'est pas configurée, ou pour piocher rapidement.
export const CHALLENGE_LIBRARY = [
  'Faire dire « ananas » à ta cible.',
  'Obtenir que ta cible te donne un objet de sa main à la tienne (stylo, verre, téléphone...).',
  'Faire trinquer ta cible avec toi.',
  'Prendre un selfie avec ta cible sans lui expliquer pourquoi.',
  'Faire en sorte que ta cible te serre la main deux fois dans la même conversation.',
  'Faire dire « c’est incroyable » à ta cible.',
  'Obtenir que ta cible t’appelle par un surnom que tu lui suggères.',
  'Faire en sorte que ta cible lise un message que tu lui montres sur ton téléphone.',
  'Faire chanter (même une seule ligne) une chanson à ta cible.',
  'Faire en sorte que ta cible te pose la question « Quelle heure est-il ? ».',
  'Faire porter un de tes accessoires (lunettes, chapeau, écharpe...) à ta cible.',
  'Obtenir que ta cible te raconte son pire souvenir de vacances.',
  'Faire en sorte que ta cible te fasse un high five.',
  'Faire goûter à ta cible quelque chose que tu lui proposes.',
  'Faire dire « Killer » à ta cible sans prononcer le mot toi-même.',
  'Faire en sorte que ta cible t’aide à porter quelque chose.',
  'Obtenir que ta cible te donne un conseil de lecture ou de film et le noter devant elle.',
  'Faire en sorte que ta cible imite un animal.',
  'Faire dire à ta cible le prénom de sa première maîtresse ou de son premier maître d’école.',
  'Faire en sorte que ta cible te prête son téléphone pour une raison crédible.',
  'Faire danser ta cible, même quelques secondes.',
  'Faire en sorte que ta cible écrive quelque chose sur un papier que tu lui tends.',
  'Faire compter ta cible jusqu’à cinq à voix haute.',
  'Faire en sorte que ta cible te recommande un restaurant.',
  'Faire dire « bonne idée » à ta cible après une proposition de ta part.',
  'Faire en sorte que ta cible te prenne en photo.',
  'Obtenir que ta cible t’explique une règle de jeu ou de sport.',
  'Faire en sorte que ta cible te verse à boire.',
  'Faire deviner une devinette à ta cible et qu’elle donne une réponse.',
  'Faire en sorte que ta cible t’accompagne quelque part (machine à café, cuisine, extérieur...).',
  'Faire dire « pourquoi pas » à ta cible.',
  'Faire en sorte que ta cible te donne l’heure en regardant sa montre ou son téléphone.',
  'Faire réciter à ta cible l’alphabet à l’envers jusqu’à « T ».',
  'Faire en sorte que ta cible tienne ton verre pendant au moins dix secondes.',
  'Obtenir que ta cible fasse un compliment à quelqu’un d’autre devant toi.',
  'Faire dire à ta cible son plat préféré.',
  'Faire en sorte que ta cible épelle son nom de famille.',
  'Faire applaudir ta cible.',
  'Faire en sorte que ta cible te montre une photo de son téléphone.',
  'Faire dire « je te jure » à ta cible.',
  'Faire en sorte que ta cible raconte une blague.',
  'Faire en sorte que ta cible t’emprunte quelque chose.',
  'Faire dire un mot en anglais à ta cible au milieu d’une phrase en français.',
  'Faire en sorte que ta cible se lève pour toi (lui demander de l’aide, de la place...).',
  'Faire en sorte que ta cible te fasse un câlin.',
  'Faire jouer ta cible à pierre-feuille-ciseaux avec toi.',
  'Faire en sorte que ta cible te donne son avis sur ta tenue.',
  'Faire dire « c’est pas faux » à ta cible.',
  'Faire en sorte que ta cible t’explique comment elle est venue aujourd’hui.',
  'Faire en sorte que ta cible t’ouvre une porte.',
];
